[book]
authors = ["Zach Harel"]
language = "en"
multilingual = false
src = "src"
title = "expressway-docs"

[output.html]
additional-css = ["theme/css/catppuccin.css"]
default-theme = "latte"
preferred-dark-theme = "macchiato"
mathjax-support = true